// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfIu1qjuyCsxjbxqjijUOE18q9f5Ped7I',
    appId: '1:719150668758:web:b60d12017db5fae865a277',
    messagingSenderId: '719150668758',
    projectId: 'circlehome-8de10',
    authDomain: 'circlehome-8de10.firebaseapp.com',
    storageBucket: 'circlehome-8de10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArWi11WoDuTzWpvEJOteKKNNaRT8XkhHw',
    appId: '1:719150668758:android:919f36bcc59d7b6765a277',
    messagingSenderId: '719150668758',
    projectId: 'circlehome-8de10',
    storageBucket: 'circlehome-8de10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChhaJh8QKLzJuXXa0vJUwxLBEDuRw_Uzs',
    appId: '1:719150668758:ios:d024b205209c4f8d65a277',
    messagingSenderId: '719150668758',
    projectId: 'circlehome-8de10',
    storageBucket: 'circlehome-8de10.firebasestorage.app',
    iosBundleId: 'com.example.circlehome',
  );

}